# Generated by Django 5.2.6 on 2025-10-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-poçt')),
                ('subject', models.CharField(max_length=200, verbose_name='Mövzu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('status', models.CharField(choices=[('new', 'Yeni'), ('read', 'Oxundu'), ('replied', 'Cavablandı'), ('spam', 'Spam')], default='new', max_length=10, verbose_name='Status')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Ünvanı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Göndərilmə Tarixi')),
            ],
            options={
                'verbose_name': 'Kontakt Mesajı',
                'verbose_name_plural': 'Kontakt Mesajları',
                'ordering': ['-created_at'],
            },
        ),
    ]
