# Generated by Django 5.2.6 on 2025-10-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon Nömrəsi')),
                ('email', models.EmailField(max_length=254, verbose_name='E-poçt')),
                ('address', models.TextField(verbose_name='Ünvan')),
            ],
            options={
                'verbose_name': 'Əlaqə Məlumatı',
                'verbose_name_plural': 'Əlaqə Məlumatları',
            },
        ),
    ]
