# Generated by Django 5.2.6 on 2025-11-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_contact_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='project_type',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Backend Development', 'Backend Development'), ('API Development', 'API Development'), ('Consultation', 'Consultation'), ('Other', 'Other')], default=1, max_length=50, verbose_name='Layihə Növü'),
            preserve_default=False,
        ),
    ]
