# Generated by Django 5.2.6 on 2025-11-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_contact_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='project_type',
            field=models.CharField(blank=True, choices=[('Web Development', 'Web Development'), ('Backend Development', 'Backend Development'), ('API Development', 'API Development'), ('Consultation', 'Consultation'), ('Other', 'Other')], max_length=50, null=True, verbose_name='Layihə Növü'),
        ),
    ]
