# Generated by Django 5.2.6 on 2025-10-31 19:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kateqoriya adı')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Kateqoriya',
                'verbose_name_plural': 'Kateqoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Teq adı')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Teq',
                'verbose_name_plural': 'Teqlər',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField(verbose_name='Məzmun')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Qısa məzmun')),
                ('post_type', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('fullstack', 'FullStack'), ('hamsi', 'Hamsı')], default='hamsi', max_length=20, verbose_name='Post Tipi')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Nəşr tarixi')),
                ('reading_time', models.PositiveIntegerField(default=5, verbose_name='Oxuma müddəti (dəq)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Nəşr edilib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category', verbose_name='Kateqoriya')),
                ('tags', models.ManyToManyField(blank=True, to='blog.tag', verbose_name='Teqlər')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Postlar',
                'ordering': ['-published_date'],
            },
        ),
    ]
