# Generated by Django 5.2.6 on 2025-11-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_type',
            field=models.CharField(choices=[('backend', 'Backend Development'), ('frontend', 'Frontend Development'), ('fullstack', 'FullStack Development'), ('devops', 'DevOps')], max_length=50, verbose_name='Post Tipi'),
        ),
    ]
