# Generated by Django 5.2.6 on 2025-11-01 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_post_type'),
        ('home', '0002_alter_about_options_alter_codedeveloper_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.icons', verbose_name='İkon'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='Blog şəkli'),
        ),
    ]
