# Generated by Django 5.2.6 on 2025-11-02 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_icon_blogpost_image'),
        ('home', '0002_alter_about_options_alter_codedeveloper_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.icons', verbose_name='İcon'),
        ),
    ]
