# Generated by Django 5.2.6 on 2025-11-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogpost_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug_az',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug_en',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug_tr',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
