# Generated by Django 5.2.6 on 2025-11-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogpost_slug_az_blogpost_slug_en_blogpost_slug_tr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content_az',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='content_tr',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='excerpt_az',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='excerpt_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='excerpt_tr',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='slug_az',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='slug_tr',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title_az',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title_tr',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_type',
            field=models.CharField(choices=[('Backend Development', 'backend'), ('Frontend Development', 'frontend'), ('FullStack Development', 'fullstack'), ('DevOps', 'devops')], max_length=50, verbose_name='Post Tipi'),
        ),
    ]
