# Generated by Django 5.2.6 on 2025-11-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_blogpost_content_az_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_type',
            field=models.CharField(blank=True, choices=[('Backend Development', 'backend'), ('Frontend Development', 'frontend'), ('FullStack Development', 'fullstack'), ('DevOps', 'devops')], max_length=50, null=True, verbose_name='Post Tipi'),
        ),
    ]
