# Generated by Django 5.2.6 on 2025-11-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blogpost_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_az',
            field=models.TextField(null=True, verbose_name='Məzmun'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Məzmun'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_tr',
            field=models.TextField(null=True, verbose_name='Məzmun'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_az',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Qısa məzmun'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_en',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Qısa məzmun'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_tr',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Qısa məzmun'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_az',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq'),
        ),
    ]
