# Generated by Django 5.2.6 on 2025-11-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogpost_content_az_blogpost_content_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Post Tipi'),
        ),
    ]
