# Generated by Django 5.2.6 on 2025-11-01 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Haqqında Bölmə', 'verbose_name_plural': 'Haqqında Bölmələr'},
        ),
        migrations.AlterModelOptions(
            name='codedeveloper',
            options={'verbose_name': 'Kod Tərtibatçısı', 'verbose_name_plural': 'Kod Tərtibatçıları'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date'], 'verbose_name': 'Təcrübə', 'verbose_name_plural': 'Təcrübələr'},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Ana Səhifə', 'verbose_name_plural': 'Ana Səhifələr'},
        ),
        migrations.AlterModelOptions(
            name='icons',
            options={'ordering': ['name'], 'verbose_name': 'İcon', 'verbose_name_plural': 'İconlar'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name'], 'verbose_name': 'Bacarıq', 'verbose_name_plural': 'Bacarıqlar'},
        ),
        migrations.AlterModelOptions(
            name='skillscategory',
            options={'ordering': ['name'], 'verbose_name': 'Bacarıq Kateqoriyası', 'verbose_name_plural': 'Bacarıq Kateqoriyaları'},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ['name'], 'verbose_name': 'Sosial Link', 'verbose_name_plural': 'Sosial Linklər'},
        ),
        migrations.AlterModelOptions(
            name='typingtext',
            options={'ordering': ['text'], 'verbose_name': 'Yazı Tipi Mətn', 'verbose_name_plural': 'Yazı Tipi Mətnlər'},
        ),
    ]
