# Generated by Django 5.2.6 on 2025-11-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_about_options_alter_codedeveloper_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codedeveloper',
            old_name='about',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='codedeveloper',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='codedeveloper',
            name='name',
        ),
        migrations.RemoveField(
            model_name='codedeveloper',
            name='passion',
        ),
        migrations.RemoveField(
            model_name='codedeveloper',
            name='skills',
        ),
    ]
