# Generated by Django 5.2.6 on 2025-11-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='content_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='content_tr',
            field=models.TextField(null=True),
        ),
    ]
