# Generated by Django 5.2.6 on 2025-11-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_about_content_az_about_content_en_about_content_tr'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='end_date_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='end_date_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='end_date_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='job_title_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='job_title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='job_title_tr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
