# Generated by Django 5.2.6 on 2025-10-31 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_technology_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Technology',
            new_name='TechnologyTag',
        ),
    ]
