# Generated by Django 5.2.6 on 2025-11-02 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_technology_technologytag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Layihə', 'verbose_name_plural': 'Layihələr'},
        ),
        migrations.AlterModelOptions(
            name='projectlink',
            options={'verbose_name': 'Layihə Linki', 'verbose_name_plural': 'Layihə Linkləri'},
        ),
        migrations.AlterModelOptions(
            name='technologytag',
            options={'ordering': ['name'], 'verbose_name': 'Texnologiya Tagı', 'verbose_name_plural': 'Texnologiya Tagları'},
        ),
    ]
