# Generated by Django 5.2.6 on 2025-11-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_options_alter_projectlink_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=2, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
