# Generated by Django 5.2.6 on 2025-11-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
