# Generated by Django 5.2.6 on 2025-11-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
