# Generated by Django 5.2.6 on 2025-11-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_tr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
